#!/usr/bin/env bash
#
# lib/profiles/kubeadm.sh — the "Debian 13 + kubeadm" profile (Vagrant-KubeADM repository).
#
# What this profile says, in one sentence: the OS is an ORDINARY Linux. Nothing is read-only,
# systemd is there, packages install (`open-iscsi` for Longhorn), and PodSecurity admission
# enforces NO level cluster-wide by default. Most of the workarounds written for Talos are
# therefore pointless here — we document them as such instead of deleting them, so that the
# comparison stays readable.
#
# The flip side: `kubeadm init` installs NO pod network (nodes stay NotReady until the CNI
# layer lands) and kube-proxy is OPTIONAL — it can be replaced by Cilium in eBPF
# (`KUBE_PROXY_REPLACEMENT=true`, the lab default).

# shellcheck shell=bash

DISTRO_LABEL="Debian 13 + kubeadm"
LAB_REPO_NAME="Vagrant-KubeADM"          # neighbouring Vagrant repository (lab.env, _out/)
DEFAULT_LAB_DOMAIN="kubeadm.lab.example.io"
CA_ORG="Vagrant-KubeADM lab"             # subject of the self-signed CA (self-signed/)
CA_FILE_NAME="vagrant-kubeadm-lab.crt"   # suggested name when importing into the trust store
CLUSTER_UP_HINT="./kubeadm/cluster-up.sh (Vagrant-KubeADM repository)"
CLUSTER_RESET_HINT="./kubeadm/cluster-reset.sh && ./kubeadm/cluster-up.sh"

# --- Network -----------------------------------------------------------------
# Host-only interface: Debian 13 uses predictable names (`enp0s8`) but some Vagrant boxes keep
# `eth1`. cluster-up.sh DETECTS it inside the VM and writes it to `_out/cluster.env` — this
# default is only a last resort.
DEFAULT_HOSTONLY_IF="eth1"
# Pod CIDR: `networking.podSubnet` passed to `kubeadm init`.
DEFAULT_POD_CIDR="10.244.0.0/16"
# kube-proxy replaceable in eBPF by Cilium (the kubeadm lab default).
KUBE_PROXY_REPLACEABLE=true
DEFAULT_KUBE_PROXY_REPLACEMENT="true"
# The kubeadm lab is HA: the apiserver is reached through the keepalived VIP, never through
# cp1's IP (the VIP survives losing cp1, and it is the one in the certificates).
DEFAULT_VIP="192.168.56.5"
# flannel: NO CNI is installed at bootstrap, so it is up to the platform layer to install it
# (the flannel/flannel chart).
FLANNEL_PRE_INSTALLED=false

# --- Cilium ------------------------------------------------------------------
# On Debian the chart defaults are the right ones: the chart mounts cgroup2 itself and works
# out the agent capabilities. The `cgroup.autoMount.enabled=false`, `cgroup.hostRoot` and
# `securityContext.capabilities.*` that Cilium documents are specific to Talos — here they
# would be HARMFUL.
CILIUM_IPAM_MODE="cluster-pool"          # the pod pool is managed by the Cilium operator
cilium_specific_sets() { :; }            # nothing to add

# --- Storage -----------------------------------------------------------------
# local-path-provisioner: the UPSTREAM path. On Debian 13 `/opt` is writable and the helper
# pod creates it without asking anyone.
LOCAL_PATH_DIR="/opt/local-path-provisioner"
# Longhorn: the iSCSI prerequisite is a PACKAGE (`open-iscsi`, installed by
# kubeadm/provision.sh), not a system-image extension — nothing to check or patch before the
# chart, and `/var/lib/longhorn` is an ordinary directory whose mount propagation is already
# fine.
LONGHORN_PREP_REQUIRED=false

# --- Security / admission ----------------------------------------------------
# No PodSecurity level enforced cluster-wide: the `privileged` labels put on namespaces unlock
# nothing TODAY. We keep them because they document what the pods actually need, and because
# they protect the day admission is hardened.
PODSECURITY_DEFAULT="(no level enforced by default)"
# trivy-operator: the node-collector bind-mounts /etc/systemd, /lib/systemd, /etc/kubernetes…
# All those paths exist and are readable on Debian → both "node" scanners work as they are.
TRIVY_NODE_COLLECTOR=true

# --- Observability -----------------------------------------------------------
# controller-manager and scheduler listen on 0.0.0.0 (bind-address set by
# kubeadm/templates/kubeadm-init.yaml.tpl) and etcd exposes its metrics on 0.0.0.0:2381: all
# three chart monitors are therefore SCRAPABLE. kube-proxy stays out of the picture (either
# absent because Cilium replaced it, or metrics on loopback only).
KPS_SCRAPE_CONTROL_PLANE=true

# --- API-server OIDC authentication (dex/) -----------------------------------
# The kube-apiserver is a STATIC POD: its manifest is a file on each control plane's disk,
# regenerated by `kubeadm` from the `kubeadm-config` ConfigMap. There is therefore no API to
# change it — you need a session on every node.
APISERVER_OIDC_PATCH="apiserver-oidc.kubeadm.yaml"
APISERVER_OIDC_MECHANISM="kubeadm-config ConfigMap + kubeadm init phase, on each control plane"
# $1 = path of the fragment to merge. Writes the commands to run on stdout: this repository
# does NOT run them, they restart the API server (see dex/README.md).
apiserver_oidc_commands() {
  cat <<EOF
    # 1. merge the fragment into the source of truth (interactive editor)
    kubectl -n kube-system edit configmap kubeadm-config     # paste the apiServer block of ${1}

    # 2. on EACH control plane, regenerate the static manifest from that ConfigMap
    vagrant ssh k8s-cp1 -c '
      kubectl -n kube-system get cm kubeadm-config -o jsonpath="{.data.ClusterConfiguration}" \\
        | sudo tee /tmp/kubeadm.yaml >/dev/null
      sudo kubeadm init phase control-plane apiserver --config /tmp/kubeadm.yaml'
    kubectl get --raw=/readyz && echo   # check BEFORE moving on to the next control plane
EOF
}

# --- Vault / VSO -------------------------------------------------------------
# Demo KV-v2 mount, specific to the lab (the HCL policies refer to it).
VAULT_KV_MOUNT="kubeadm-lab"

# --- Misc --------------------------------------------------------------------
# metrics-server: the kubelet's "serving" certificate is self-signed by the kubelet itself on
# both distributions → `--kubelet-insecure-tls` in both cases.
METRICS_KUBELET_INSECURE=true
